FROM centos:5.11

COPY ./yum.repos.d/ /etc/yum.repos.d/

RUN yum install -y gcc make tar wget

RUN rpm -ivh http://archives.fedoraproject.org/pub/archive/epel/5/x86_64/epel-release-5-4.noarch.rpm
RUN yum install -y git
